services:
  mail:
    image: bytemark/smtp:latest
    restart: always
    env_file:
      - plausible-mail.env

  plausible_db:
    image: postgres:14-alpine
    restart: always
    volumes:
      - /docker/plausible/data/db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres

  plausible_events_db:
    image: clickhouse/clickhouse-server:23.3.7.5-alpine
    restart: always
    volumes:
      - /docker/plausible/data/event-data:/var/lib/clickhouse
      - /docker/plausible/data/clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - /docker/plausible/data/clickhouse/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  plausible:
    image: plausible/analytics:latest
    restart: always
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"
    depends_on:
      - plausible_db
      - plausible_events_db
      - mail
    labels:
      - traefik.enable=true
      - traefik.http.routers.plausible.tls=true
      - traefik.http.routers.plausible.tls.certresolver=letsencrypt
      - traefik.http.routers.plausible.rule=Host(`REPLACE_ME`)
      - traefik.http.routers.plausible.entrypoints=websecure
      - traefik.http.routers.plausible.service=plausible
      - traefik.http.services.plausible.loadbalancer.server.port=8000
    env_file:
      - plausible.env
    networks:
      - default
      - traefik

networks:
  traefik:
    external: true
  default:
    external: false