services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    networks:
      - telemetry
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.jaeger.tls=true
      - traefik.http.routers.jaeger.tls.certresolver=letsencrypt
      - traefik.http.routers.jaeger.rule=Host(`REPLACE_ME`)
      - traefik.http.routers.jaeger.entrypoints=websecure
      - traefik.http.routers.jaeger.service=jaeger
      - traefik.http.services.jaeger.loadbalancer.server.port=16686
      - traefik.http.routers.jaeger.middlewares=services@file

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    volumes:
      - /docker/telemetry/data/otel-collector-config.yml:/etc/otelcol-contrib/config.yaml
    #ports:
      #- 1888:1888 # pprof extension
      #- 8888:8888 # Prometheus metrics exposed by the Collector
      #- 8889:8889 # Prometheus exporter metrics
      #- 13133:13133 # health_check extension
      #- 4317:4317 # OTLP gRPC receiver
      #- 4318:4318 # OTLP http receiver
      #- 55679:55679 # zpages extension
    networks:
      - telemetry
    depends_on:
      - jaeger

networks:
  telemetry:
    external: true
  traefik:
    external: true