services:
  traefik:
    image: traefik:3.0
    container_name: traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443/tcp"
      - "443:443/udp"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /docker/traefik/data/traefik.yml:/traefik.yml:ro
      - /docker/traefik/data/traefik_dynamic.yml:/traefik_dynamic.yml:ro
      - /docker/traefik/data/acme.json:/acme.json
    env_file:
      - traefik.env
    networks:
      - traefik
      - telemetry

networks:
  traefik:
    external: true
  telemetry:
    external: true