services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mailserver
    # Provide the FQDN of your mail server here (Your DNS MX record should point to this value)
    hostname: REPLACE_ME
    env_file: mailserver.env
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS, Authentication is DISABLED => use port 465/587 instead)
      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
    volumes:
      - /docker/mailserver/data/dms/mail-data/:/var/mail/
      - /docker/mailserver/data/dms/mail-state/:/var/mail-state/
      - /docker/mailserver/data/dms/mail-logs/:/var/log/mail/
      - /docker/mailserver/data/dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
      - /docker/traefik/data/acme.json:/etc/letsencrypt/acme.json:ro
    restart: unless-stopped
    stop_grace_period: 1m
    cap_add:
       - NET_ADMIN
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0
    networks:
      - mailserver
      - lldap

  autodiscover:
    image: monogramm/autodiscover-email-settings:latest
    container_name: autodiscover
    restart: unless-stopped
    env_file:
      - autodiscover.env
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.autodiscover.tls=true
      - traefik.http.routers.autodiscover.tls.certresolver=letsencrypt
      - traefik.http.routers.autodiscover.rule=Host(`REPLACE_ME`) || Host(`REPLACE_ME`)
      - traefik.http.routers.autodiscover.entrypoints=websecure
      - traefik.http.routers.autodiscover.service=autodiscover
      - traefik.http.services.autodiscover.loadbalancer.server.port=8000

  snappymail:
    image: djmaze/snappymail:latest
    container_name: snappymail
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.snappymail.rule=Host(`REPLACE_ME`) || Host(`REPLACE_ME`)
      - traefik.http.routers.snappymail.entrypoints=websecure
      - traefik.http.routers.snappymail.service=snappymail
      - traefik.http.services.snappymail.loadbalancer.server.port=8888
    volumes:
      - /docker/mailserver/data/snappymail:/var/lib/snappymail
    networks:
      - traefik

networks:
  mailserver:
    enable_ipv6: true
  traefik:
    external: true
  lldap:
    external: true