services:
  wg-easy:
    environment:
      - WG_HOST=REPLACE_ME
      - PASSWORD=REPLACE_ME
      - WG_PORT=REPLACE_ME
      - WG_DEFAULT_ADDRESS=10.8.0.x
      - WG_DEFAULT_DNS=1.1.1.1
      - UI_TRAFFIC_STATS=true
    image: ghcr.io/wg-easy/wg-easy:latest
    container_name: wg-easy
    volumes:
      - /docker/wireguard/data:/etc/wireguard
    ports:
      - "REPLACE_ME/udp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.wireguard.tls=true
      - traefik.http.routers.wireguard.tls.certresolver=letsencrypt
      - traefik.http.routers.wireguard.rule=Host(`REPLACE_ME`)
      - traefik.http.routers.wireguard.entrypoints=websecure
      - traefik.http.routers.wireguard.service=wireguard
      - traefik.http.services.wireguard.loadbalancer.server.port=51821

networks:
  traefik:
    external: true